### PR TITLE
fixed to work on of-10.1

### PR DESCRIPTION
**Pull request by maro525**
changed programs a bit to work on openframeworks v10.1

### CODE REVIEW

**Comment by paulvollmer** [comment]
@maro525 the PR is a bit verbose because of the coding style changes. can you only push the relevant changes please. then it's easier to review.

thank you

**Comment by paulvollmer** [comment]
i saw @tado did it already. we can merge tado's master instead

https://github.com/paulvollmer/ofxCsv/compare/master...tado:master

**Comment by maro525** [comment]
> @maro525 the PR is a bit verbose because of the coding style changes. can you only push the relevant changes please. then it's easier to review.
> 
> thank you

i see.  
i found it was because of my auto format function. 
and it was too verbose..

**Comment by paulvollmer** [comment]
i created a PR with @tado 's fix #35

**Pull request closed without merging**
